WARNING: S3 S3_init:512 (path:ior777) "ErrorInternalError": We encountered an internal error. Please try again. 
-- started at 12/13/2020 13:09:16 --

mdtest-3.4.0+dev was launched with 2 total task(s) on 2 node(s)
Command line used: ./mdtest '-n' '1000000' '-t' '-w' '3901' '-e' '3901' '-P' '-N' '1' '-F' '-d' './datafiles/2020.12.13-11.48.46/mdtest-hard' '-x' './results/2020.12.13-11.48.46/mdtest-hard.stonewall' '-E' '-X' '-a' 'S3-libs3' '--S3-libs3.host=storage.googleapis.com' '--S3-libs3.secret-key=foo' '--S3-libs3.access-key=foo' '--S3-libs3.s3-compatible' '--S3-libs3.use-ssl' '--S3-libs3.location=EU'
Path                : ./datafiles/2020.12.13-11.48.46/mdtest-hard
FS                  : 0.0 GiB   Used FS: 0.0%   Inodes: 0.0 Mi   Used Inodes: -inf%
Nodemap: 10
V-0: Rank   0 Line  2203 Shifting ranks by 1 for each phase.
2 tasks, 2000000 files

SUMMARY rate: (of 1 iterations)
   Operation                      Max            Min           Mean        Std Dev
   ---------                      ---            ---           ----        -------
   File creation             :          0.000          0.000          0.000          0.000
   File stat                 :          0.000          0.000          0.000          0.000
   File read                 :         18.898         18.898         18.898          0.000
   File removal              :          0.000          0.000          0.000          0.000
   Tree creation             :          0.000          0.000          0.000          0.000
   Tree removal              :          0.000          0.000          0.000          0.000

SUMMARY time: (of 1 iterations)
   Operation                      Max            Min           Mean        Std Dev
   ---------                      ---            ---           ----        -------
   File creation             :          0.000          0.000          0.000          0.000
   File stat                 :          0.000          0.000          0.000          0.000
   File read                 :        132.927        132.926        132.927          0.001
   File removal              :          0.000          0.000          0.000          0.000
   Tree creation             :          0.000          0.000          0.000          0.000
   Tree removal              :          0.000          0.000          0.000          0.000
-- finished at 12/13/2020 13:11:30 --

WARNING: S3 S3_final:524 (path:ior777) "ErrorBucketNotEmpty": The bucket you tried to delete is not empty. 
